services:
    db:
        image: postgres:13.2-alpine
        volumes:
        - ./data/db:/var/lib/postgresql/data
        - ./scripts/db:/scripts/db/
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
    redis:
        image: redis:6.2.2-alpine
        ports:
            - "6379:6379"
